### ISSUE TITLE
The object length read (982908999) for type None at path [...] cannot exceed the remaining size (24967) of the stream!

### ISSUE THREAD

**Issue by laloutre87** [replaysMike/AnySerializer#22]
Hi. 

I'm trying to make .Net Core sessions  behave the same way they did in regular .Net ( allowing  to store object of any kind, as it wasn't necessary to serialize ),  so I need to be able to serialize anything,  and this library is the closest I got to managing that so far.

But it still crashes in some cases. 

For example if an object  X   has a field of type  List\<A\>   containing objects of type B and C, inheriting from A , the error in this issue title is encountered. 

As far as I can see, it's because in TypeWriter,  obj.GetFields(FieldOptions.AllWritable) is  called on the object of type B,  returning all fields of type B,    but when deserializing the List\<A\> ,  the GetFields(FieldOptions.AllWritable)  is called on an object of type A. 

I though the option " SerializerOptions.EmbedTypes" would help, but in fact it doesn't ( as stated in the project wiki, as it only applies to interfaces and anonymous type ) .

**Comment by laloutre87** [comment]
Removing both " && !newTypeSupport.IsConcreteType "  in WriteObject seems to avoid the crash,  but conditions are rarely there for nothing, so I assume this change breaks something else. 

Also it's not enough to deserialize correctly the data.  Because in WriteEnumerableType ( and WriteDictionaryType, ... ),  the concrete type is evaluated once for the full loop (due to the condition   " elementConcreteExtendedType is null " ) , so every object in the list will be stored with the type of the first element of the List.  

I switched for something like that : 

 var elementType = item?.GetType();    
if (item != null && elementConcreteExtendedType?.ConcreteType != elementType)
    elementConcreteExtendedType = elementType.GetExtendedType();

It's probably slower, but i don't think it's avoidable to check the type of each object separately.

**Comment by frankabbruzzese** [comment]
Basically, this serislizer at moment doesnt support polymorphism.

It needs a new option for polymorphism, that, when on, always adds type if different from root type. 

The modificatiin should be easy. 

I hope this will be done, since support for BinaryFormatter will be removed from. Net, so at moment this project appears to be the unic option to serialize general object graphs.

**Comment by laloutre87** [comment]
Well, the above mentioned modification seems to work  for me for complex objects ...   but i still encounter errors on deserializing very large lists.  I must hit some kind of maximum data size .  There is an "ExceedsMaxSizeException" class defined, but it's only thrown when using the "compact" mode, so I'm not sure.

**Comment by frankabbruzzese** [comment]
@laloutre87 ,
Your modification doesn't work for me. It is not able to deserialize the subclass but always serializes the base class, in the wrong way (giving to base class properties values of properties of descendant classes. Sometimes deserialization throw exceptions not due to some max size, but to the fact it is not able to deserialize properly. Basically, it performs the right count of the object size but it misunderstand the type.
