### ISSUE TITLE
Replace lz4net dependency with K4os.Compression.LZ4

### ISSUE THREAD

**Issue by TechInterMezzo** [replaysMike/AnySerializer#7]
If you look at the github site of lz4net, you can see that it is no longer mantained and replaced by K4os.Compression.LZ4. It is the same author.

https://github.com/MiloszKrajewski/lz4net
https://github.com/MiloszKrajewski/K4os.Compression.LZ4

K4os.Compression.LZ4 is only compatible with net4.6+, so you would have to drop support for net4.0 and net 4.5.

I already updated the solution locally and it works, but the test "Should_Compress_BeSmaller_OnLargeObjects" fails. The new compression ratio is "only" 28.13 instead of 33.29. I guess that could be improved by changing the compression level, but I don't think it's that important.

Since there are some pitfalls I don't know if I should make a PR. But I think it would be more future proof to use the new library.

**Comment by replaysMike** [comment]
Hi @TechInterMezzo - yup I am considering dropping .net 4.0 support in order to switch, I just didn't have a compelling reason to do so yet. That test that fails is not a great test in terms of what it's testing but interesting to note that the older version gets a better compression ratio.

I will definitely take a look - was there a particular reason why the old one wasn't working for you? or was it just because it's not maintained anymore?

**Comment by TechInterMezzo** [comment]
It's working fine. It's just that I stumbled across the dependencies on NuGet and saw the GitHub page recommending the new package. So it's just a better feeling to be future proof I guess. The management of legacy dependencies and their dependencies can sometimes be a beast developing for netstandard (respectively netcore and netfx).

I really like to study the code of other developers and learn from them.
Great library btw.

**Comment by replaysMike** [comment]
This is now in version 1.1.0 - note that means compression is unavailable below .net framework 4.6
